### PR TITLE
Fix postman to avoid errors. Update notes.

### PR DESCRIPTION
**Pull request by rebekaburnett**

### CODE REVIEW

**Comment by rebekaburnett** [comment]
@SvenErikPy - I was getting an error this time when I ran it. I updated the body of the first request so that isPickupPoint and isPorterbuddy were not both true. Also set value to 0 for the option with porterbuddy. 
But, I am not sure about the id and brand, as they are both "posten", but isPorterbuddy is true. Is that a problem?
`   "fixedOptions": [
      {
        "amount": {
          "currency": "{{currency}}",
          "value": "0"
        },
        "id": "postenservicepakke1",
        "priority": 1,
        "brand": "Posten",
        "product": "home delivery",
        "isDefault": true,
        "description": "Your package is delivered to your home.",
        "isPickupPoint": false,
        "isPorterbuddy": true
      },
      {
        "amount": {
          "currency": "{{currency}}",
          "value": "{{amount}}"
        },
        "id": "postenservicepakke2",
        "priority": 2,
        "brand": "Posten",
        "product": "pick-up in store",
        "isDefault": false,
        "description": "Pick up your package at the local store.",
        "isPickupPoint": true,
        "isPorterbuddy": false
      }`

**Comment by SvenErikPy** [comment]
The id and brand is not yet important, but should probably be updated to cause less confusion.  The rest is okay. So I think your changes are okay,  but looking more carefully at it will have to wait until tomorrow.

Få Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rebekaburnett** [comment]
Tomorrow is good. :-) We can fix the brand here, if you want. :-)

**Comment by SvenErikPy** [comment]
If we just remove "Isporterbuddy" from the first option, I think the brand etc. can remain as is

**Comment by rebekaburnett** [comment]
But then you don't have a porterbuddy example. But I guess that's ok?

**Comment by rebekaburnett** [comment]
How about if I do that, and then add a porterbuddypakke example afterwards? Like this:
```
"fixedOptions": [
      {
        "amount": {
          "currency": "{{currency}}",
          "value": "{{amount}}"
        },
        "id": "postenservicepakke1",
        "priority": 1,
        "brand": "Posten",
        "product": "home delivery",
        "isDefault": true,
        "description": "Your package is delivered to your home.",
        "isPickupPoint": false,
        "isPorterbuddy": false
      },
      {
        "amount": {
          "currency": "{{currency}}",
          "value": "{{amount}}"
        },
        "id": "postenservicepakke2",
        "priority": 2,
        "brand": "Posten",
        "product": "pick-up in store",
        "isDefault": false,
        "description": "Pick up your package at the local store.",
        "isPickupPoint": true,
        "isPorterbuddy": false
      },
      {
        "amount": {
          "currency": "{{currency}}",
          "value": "0"
        },
        "id": "porterbuddypakke",
        "priority": 1,
        "brand": "Porterbuddy",
        "product": "home delivery",
        "isDefault": true,
        "description": "Your package is delivered to your home.",
        "isPickupPoint": false,
        "isPorterbuddy": true
      }
    ],
```

**Review by SvenErikPy — APPROVED** [review]

**Pull request merged**
